version: '3'

vars:
  BINARY_NAME: smtpd
  BUILD_DIR: ./bin

tasks:
  default:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: all

  build:
    desc: Build the Go binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/smtpd
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vulncheck:
    desc: Run govulncheck for security vulnerabilities
    cmds:
      - govulncheck ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  all:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: build
      - task: lint
      - cmd: task vulncheck
        ignore_error: true
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  install:deps:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  hooks:install:
    desc: Configure git to use the project hooks directory
    cmds:
      - git config core.hooksPath .githooks
      - echo "Git hooks installed from .githooks directory"

  serve:
    desc: Start local SMTP server with maildir delivery to temp directory
    vars:
      MAILDIR:
        sh: mktemp -d -t smtpd-maildir-XXXXXX
    cmds:
      - echo "Maildir storage: {{.MAILDIR}}"
      - go run ./cmd/smtpd -listen localhost:2525 -maildir {{.MAILDIR}} -log-level debug