version: '3'

vars:
  BINARY_NAME: smtpd
  BUILD_DIR: ./bin

tasks:
  default:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: all

  build:
    desc: Build the Go binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/smtpd
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vulncheck:
    desc: Run govulncheck for security vulnerabilities
    cmds:
      - govulncheck ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  all:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: build
      - task: lint
      - cmd: task vulncheck
        ignore_error: true
      - task: test

  release:
    desc: Tag and push a release (usage: task release VERSION=0.0.1)
    cmds:
      - test -n "{{.VERSION}}" || (echo "VERSION is required: task release VERSION=0.0.x" && exit 1)
      - git tag v{{.VERSION}}
      - git push origin v{{.VERSION}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  install:deps:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  hooks:install:
    desc: Configure git to use the project hooks directory
    cmds:
      - git config core.hooksPath .githooks
      - echo "Git hooks installed from .githooks directory"

  serve:
    desc: Start local SMTP server with maildir delivery to temp directory
    vars:
      DELIVERY_PATH:
        sh: mktemp -d -t smtpd-maildir-XXXXXX
    cmds:
      - 'echo "Delivery storage: {{.DELIVERY_PATH}}"'
      - go run ./cmd/smtpd -listen localhost:2525 -delivery-type maildir -delivery-path {{.DELIVERY_PATH}} -log-level debug

  test:swaks:
    desc: Run SMTP integration tests using swaks
    cmds:
      - ./test/swaks/run_tests.sh

  test:swaks:tls:
    desc: Run SMTP TLS integration tests using swaks
    cmds:
      - ./test/swaks/run_tls_tests.sh

  test:swaks:all:
    desc: Run all swaks integration tests (basic + TLS)
    cmds:
      - task: test:swaks
      - task: test:swaks:tls

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t infodancer-smtpd:latest .

  docker:run:
    desc: Run smtpd container with domain-aware storage
    vars:
      CONFIG_PATH:
        sh: mktemp -d -t smtpd-config-XXXXXX
      STORAGE_PATH:
        sh: mktemp -d -t smtpd-storage-XXXXXX
    cmds:
      - 'echo "Config: {{.CONFIG_PATH}}, Storage: {{.STORAGE_PATH}}"'
      - |
        docker run -p 2525:25 \
          -v {{.CONFIG_PATH}}:/etc/infodancer:ro \
          -v {{.STORAGE_PATH}}:/var/infodancer \
          -e SMTPD_HOSTNAME=localhost \
          -e SMTPD_DELIVERY_TYPE=maildir \
          -e SMTPD_DELIVERY_PATH=/var/infodancer/domains \
          -e SMTPD_DELIVERY_PATH_TEMPLATE='{domain}/users/{localpart}' \
          -e SMTPD_DELIVERY_MAILDIR_SUBDIR=Maildir \
          -e SMTPD_LOG_LEVEL=debug \
          infodancer-smtpd:latest
